Added Rancher resources created by SkeltonThatcher Consulting Ltd
jmreicha/awesome-rancher pull request #6
Opened 2017-03-15 18:19 UTC by richbos

Link to Git repo containing Terraform scripts to deploy single node Rancher server with multi-AZ hosts in AWS.

Link to accompanying blog post expanding on the method and scripts contained within the Git repo.

2017-03-16 16:13 UTC, jmreicha requested changes

2017-03-16 16:13 UTC, jmreicha commented on README.md
> +* [Rancher server single node HA and multi-AZ Rancher hosts in AWS](https://github.com/SkeltonThatcher/aws-terraform-rancher-single-node-ha) - Terraform scripts to deploy Rancher server single node H
Would you mind moving this down to the Terraform section?  I think it makes more sense to put in there.

2017-03-17 09:18 UTC, richbos commented on README.md
> +* [Rancher server single node HA and multi-AZ Rancher hosts in AWS](https://github.com/SkeltonThatcher/aws-terraform-rancher-single-node-ha) - Terraform scripts to deploy Rancher server single node H
Yes, I agree, it is a better place for it. I have made the change as requested.

2017-03-17 16:55 UTC, jmreicha approved these changes

2017-03-17 16:55 UTC, merged